# Netlify Build Configuration
# This file prevents automatic plugin detection

[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.11.0"

# Disable automatic framework detection
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true
