[build]
  publish = "out"
  command = "node build-script.js"

[build.environment]
  NODE_VERSION = "20"

# Pinned Next.js plugin version to avoid dependency conflicts
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Static site configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
